import type { Company } from "@/types";

export const companies: Company[] = [
  { id: 1, slug: "gdh-559", nameTh: "จีดีเอช 559", nameEn: "GDH 559", type: "production", logoUrl: "https://image.tmdb.org/t/p/w200/eZ0mCVFpQnGsJFwcWsCRSuLHceR.png", website: "https://www.gdh559.com", description: "บริษัทผลิตภาพยนตร์ชั้นนำของไทย", founded: 2016, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 2, slug: "sahamongkol-film", nameTh: "สหมงคลฟิล์ม อินเตอร์เนชั่นแนล", nameEn: "Sahamongkol Film International", type: "production", logoUrl: "https://image.tmdb.org/t/p/w200/sN6jnVjYVp8XjTUrqJb0r0d8gVH.png", website: "https://www.sahamongkolfilm.com", description: "ผู้ผลิตและจัดจำหน่ายภาพยนตร์รายใหญ่", founded: 1970, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 3, slug: "five-star-production", nameTh: "ไฟว์สตาร์ โปรดักชั่น", nameEn: "Five Star Production", type: "production", logoUrl: "https://image.tmdb.org/t/p/w200/eFStGiSGX4V3UG4xQ3lR2QQRCjy.png", website: null, description: "บริษัทผลิตภาพยนตร์และละครโทรทัศน์", founded: 1986, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 4, slug: "channel-3", nameTh: "ไทยทีวีสีช่อง 3", nameEn: "Channel 3", type: "broadcaster", logoUrl: "https://image.tmdb.org/t/p/w200/jJXJLJNzFqECULlNyhBjc9MGgSb.png", website: "https://www.ch3thailand.com", description: "สถานีโทรทัศน์ช่อง 3", founded: 1970, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 5, slug: "channel-7", nameTh: "สถานีโทรทัศน์สีกองทัพบกช่อง 7", nameEn: "Channel 7", type: "broadcaster", logoUrl: "https://image.tmdb.org/t/p/w200/nBp4kRGaQlYTq1BPjNUj1alqSvD.png", website: "https://www.ch7.com", description: "สถานีโทรทัศน์ช่อง 7", founded: 1967, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 6, slug: "gmm-tv", nameTh: "จีเอ็มเอ็ม ทีวี", nameEn: "GMM TV", type: "production", logoUrl: "https://image.tmdb.org/t/p/w200/yExgxGJPFV6mzVqNDX7Ds2yRjKu.png", website: "https://www.gmmtv.com", description: "ผลิตละครและซีรีส์สำหรับคนรุ่นใหม่", founded: 2013, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 7, slug: "gth", nameTh: "จีทีเอช", nameEn: "GTH", type: "production", logoUrl: "https://image.tmdb.org/t/p/w200/b6FBBmqamBVh2BQAGQ0iCirqfEG.png", website: null, description: "บริษัทผลิตภาพยนตร์ (ต้นกำเนิด GDH)", founded: 2003, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 8, slug: "workpoint", nameTh: "เวิร์คพอยท์ เอ็นเทอร์เทนเมนท์", nameEn: "Workpoint Entertainment", type: "broadcaster", logoUrl: "https://image.tmdb.org/t/p/w200/2tDyamqdbKz4EBd4Vpu5r5m2GVq.png", website: "https://www.workpointtv.com", description: "ผลิตรายการโทรทัศน์และคอนเทนต์", founded: 1989, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 9, slug: "nadao-bangkok", nameTh: "นาดาว บางกอก", nameEn: "Nadao Bangkok", type: "production", logoUrl: "https://image.tmdb.org/t/p/w200/lK2RJHoFPgzAGSl9xMPWn7bMpJQ.png", website: null, description: "บริษัทบริหารศิลปินและผลิตผลงาน", founded: 2014, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 10, slug: "phranakorn-film", nameTh: "พระนครฟิลม์", nameEn: "Phranakorn Film", type: "production", logoUrl: "https://image.tmdb.org/t/p/w200/u5FqECQKGswoQrGuhOQ3TTnH2pj.png", website: null, description: "ผลิตภาพยนตร์ไทยแนวตลกและสยองขวัญ", founded: 2006, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
];
