import type { Company } from "@/types";

export const companies: Company[] = [
  { id: 1, slug: "gdh-559", nameTh: "จีดีเอช 559", nameEn: "GDH 559", type: "production", logoUrl: "/images/companies/gdh-559.svg", website: "https://www.gdh559.com", description: "บริษัทผลิตภาพยนตร์ชั้นนำของไทย ผู้สร้างสรรค์ผลงานอย่าง พี่มาก..พระโขนง, ฉลาดเกมส์โกง และ Friend Zone ที่ประสบความสำเร็จทั้งในประเทศและต่างประเทศ", founded: 2016, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 2, slug: "sahamongkol-film", nameTh: "สหมงคลฟิล์ม อินเตอร์เนชั่นแนล", nameEn: "Sahamongkol Film International", type: "production", logoUrl: "/images/companies/sahamongkol-film.svg", website: "https://www.sahamongkolfilm.com", description: "ผู้ผลิตและจัดจำหน่ายภาพยนตร์รายใหญ่ที่สุดของประเทศไทย ก่อตั้งมาอย่างยาวนาน เป็นผู้อยู่เบื้องหลังภาพยนตร์ไทยหลายร้อยเรื่อง", founded: 1970, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 3, slug: "five-star-production", nameTh: "ไฟว์สตาร์ โปรดักชั่น", nameEn: "Five Star Production", type: "production", logoUrl: "/images/companies/five-star-production.svg", website: null, description: "บริษัทผลิตภาพยนตร์และละครโทรทัศน์ที่มีประสบการณ์ยาวนาน เป็นผู้ผลิตผลงานคุณภาพมาตลอดหลายทศวรรษ", founded: 1986, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 4, slug: "channel-3", nameTh: "ไทยทีวีสีช่อง 3", nameEn: "Channel 3", type: "broadcaster", logoUrl: "/images/companies/channel-3.svg", website: "https://www.ch3thailand.com", description: "สถานีโทรทัศน์ช่อง 3 ผู้นำด้านละครโทรทัศน์ของไทย ผลิตละครที่ได้รับความนิยมสูงสุดหลายเรื่อง", founded: 1970, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 5, slug: "channel-7", nameTh: "สถานีโทรทัศน์สีกองทัพบกช่อง 7", nameEn: "Channel 7", type: "broadcaster", logoUrl: "/images/companies/channel-7.svg", website: "https://www.ch7.com", description: "สถานีโทรทัศน์ช่อง 7 หนึ่งในสถานีโทรทัศน์ที่เก่าแก่ที่สุดของไทย มีรายการและละครที่ได้รับความนิยมในวงกว้าง", founded: 1967, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 6, slug: "gmm-tv", nameTh: "จีเอ็มเอ็ม ทีวี", nameEn: "GMM TV", type: "production", logoUrl: "/images/companies/gmm-tv.svg", website: "https://www.gmmtv.com", description: "ผลิตละครและซีรีส์สำหรับคนรุ่นใหม่ เป็นผู้นำด้านซีรีส์วาย และคอนเทนต์สำหรับ Gen Z ที่โด่งดังไปทั่วเอเชีย", founded: 2013, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 7, slug: "gth", nameTh: "จีทีเอช", nameEn: "GTH", type: "production", logoUrl: "/images/companies/gth.svg", website: null, description: "บริษัทผลิตภาพยนตร์ในตำนาน ต้นกำเนิดของ GDH 559 ผู้สร้างปรากฏการณ์ภาพยนตร์ไทยยุคใหม่", founded: 2003, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 8, slug: "workpoint", nameTh: "เวิร์คพอยท์ เอ็นเทอร์เทนเมนท์", nameEn: "Workpoint Entertainment", type: "broadcaster", logoUrl: "/images/companies/workpoint.svg", website: "https://www.workpointtv.com", description: "ผลิตรายการโทรทัศน์และคอนเทนต์ เจ้าของรายการวาไรตี้ชื่อดังหลายรายการ", founded: 1989, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 9, slug: "nadao-bangkok", nameTh: "นาดาว บางกอก", nameEn: "Nadao Bangkok", type: "production", logoUrl: "/images/companies/nadao-bangkok.svg", website: null, description: "บริษัทบริหารศิลปินและผลิตผลงาน ก่อตั้งโดยณเดชน์ คูกิมิยะ เป็นค่ายที่รวมศิลปินรุ่นใหม่ที่มีความสามารถ", founded: 2014, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 10, slug: "phranakorn-film", nameTh: "พระนครฟิลม์", nameEn: "Phranakorn Film", type: "production", logoUrl: "/images/companies/phranakorn-film.svg", website: null, description: "ผลิตภาพยนตร์ไทยแนวตลกและสยองขวัญ เจ้าของผลงานดังอย่าง บุญชู และ พี่มาก..พระโขนง", founded: 2006, createdAt: "2024-01-01", updatedAt: "2024-01-01" },
];
