import type { Film } from "@/types";
import { genres } from "./genres";
import { companies } from "./companies";

const g = (slug: string) => genres.find((x) => x.slug === slug)!;
const c = (slug: string) => companies.find((x) => x.slug === slug)!;

export const films: Film[] = [
  { id: 1, slug: "bad-genius-2017", titleTh: "ฉลาดเกมส์โกง", titleEn: "Bad Genius", year: 2017, duration: 130, synopsisTh: "ลินน์ นักเรียนเก่งที่ใช้ความฉลาดโกงข้อสอบ STIC เพื่อช่วยเพื่อนที่ต้องการสมัครเข้าเรียนต่อมหาวิทยาลัยในออสเตรเลีย", synopsisEn: "A genius high school student runs an exam-cheating business that takes on international implications.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt6788942", status: "published", viewCount: 15420, companyId: 1, company: c("gdh-559"), genres: [g("thriller"), g("drama")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 2, slug: "pee-mak-2013", titleTh: "พี่มาก..พระโขนง", titleEn: "Pee Mak", year: 2013, duration: 105, synopsisTh: "มาก ทหารหาญที่กลับบ้านหลังสงคราม พร้อมด้วยเพื่อนทหารอีก 4 คน แต่กลับพบว่าภรรยาของเขาอาจไม่ใช่คนธรรมดา", synopsisEn: "Mak returns from war with friends to his village, but they begin to suspect his wife Nak may be a ghost.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt2700280", status: "published", viewCount: 22300, companyId: 7, company: c("gth"), genres: [g("comedy"), g("horror")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 3, slug: "nang-nak-1999", titleTh: "นางนาก", titleEn: "Nang Nak", year: 1999, duration: 100, synopsisTh: "เรื่องราวความรักของนางนากและมากพระโขนง ตำนานผีไทยที่โด่งดังที่สุด", synopsisEn: "The legendary Thai ghost story of Nang Nak and her undying love for her husband Mak.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 18900, companyId: 2, company: c("sahamongkol-film"), genres: [g("horror"), g("drama"), g("romance")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 4, slug: "ong-bak-2003", titleTh: "องค์บาก", titleEn: "Ong-Bak: Muay Thai Warrior", year: 2003, duration: 105, synopsisTh: "ติง ชาวบ้านจากชนบทที่ต้องเดินทางเข้ากรุงเทพฯ เพื่อตามหาเศียรพระพุทธรูปที่ถูกขโมย", synopsisEn: "A skilled Muay Thai fighter travels to Bangkok to retrieve a stolen Buddha head.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt0368909", status: "published", viewCount: 25600, companyId: 2, company: c("sahamongkol-film"), genres: [g("action")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 5, slug: "shutter-2004", titleTh: "ชัตเตอร์ กดติดวิญญาณ", titleEn: "Shutter", year: 2004, duration: 97, synopsisTh: "ตุน ช่างภาพหนุ่มที่พบเงาประหลาดปรากฏในรูปถ่ายของเขา หลังจากเหตุการณ์ชนคนแล้วหนี", synopsisEn: "A photographer discovers mysterious shadows in his photos after a hit-and-run accident.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt0440803", status: "published", viewCount: 19200, companyId: 7, company: c("gth"), genres: [g("horror"), g("thriller")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 6, slug: "last-life-in-the-universe-2003", titleTh: "เรื่องรัก น้อยนิด มหาศาล", titleEn: "Last Life in the Universe", year: 2003, duration: 112, synopsisTh: "เคนจิ ชายญี่ปุ่นที่อาศัยอยู่ในกรุงเทพฯ คิดจะฆ่าตัวตาย ได้พบกับนอย สาวไทยที่อยู่ในภาวะสูญเสีย", synopsisEn: "A suicidal Japanese man in Bangkok meets a Thai woman dealing with her own loss.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt0345549", status: "published", viewCount: 8700, companyId: 3, company: c("five-star-production"), genres: [g("drama"), g("romance")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 7, slug: "tom-yum-goong-2005", titleTh: "ต้มยำกุ้ง", titleEn: "Tom-Yum-Goong", year: 2005, duration: 108, synopsisTh: "คาม เดินทางไปออสเตรเลียเพื่อตามหาช้างที่ถูกขโมย ด้วยวิชามวยไทยอันเก่งกาจ", synopsisEn: "A young man goes to Australia to retrieve his stolen elephant using Muay Thai skills.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt0427954", status: "published", viewCount: 21100, companyId: 2, company: c("sahamongkol-film"), genres: [g("action")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 8, slug: "uncle-boonmee-2010", titleTh: "ลุงบุญมีระลึกชาติ", titleEn: "Uncle Boonmee Who Can Recall His Past Lives", year: 2010, duration: 114, synopsisTh: "ลุงบุญมีกำลังจะตาย ญาติที่เสียชีวิตไปแล้วกลับมาเยี่ยม เขาเริ่มระลึกถึงชาติที่แล้ว", synopsisEn: "A man on his deathbed is visited by the ghosts of his dead wife and missing son.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt1588895", status: "published", viewCount: 12400, companyId: 3, company: c("five-star-production"), genres: [g("drama")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 9, slug: "13-beloved-2006", titleTh: "13 เกมสยอง", titleEn: "13 Beloved", year: 2006, duration: 114, synopsisTh: "พุฒ พนักงานขายที่หมดตัว ได้รับโทรศัพท์ลึกลับชวนเล่นเกม 13 ด่าน ทุกด่านจะได้เงินเพิ่มขึ้น", synopsisEn: "A broke salesman receives a call inviting him to play a mysterious 13-step game for money.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt0883995", status: "published", viewCount: 16800, companyId: 2, company: c("sahamongkol-film"), genres: [g("thriller"), g("horror")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 10, slug: "fan-chan-2003", titleTh: "แฟนฉัน", titleEn: "My Girl", year: 2003, duration: 114, synopsisTh: "เรื่องราวความรักบริสุทธิ์ของเด็กชายจิ๋วกับเด็กหญิงน้อยหน่า ในชุมชนเล็กๆ สมัยปี 2523", synopsisEn: "A nostalgic coming-of-age story about childhood love in 1980s Thailand.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt0376738", status: "published", viewCount: 20100, companyId: 7, company: c("gth"), genres: [g("romance"), g("comedy"), g("drama")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 11, slug: "alone-2007", titleTh: "แฝด", titleEn: "Alone", year: 2007, duration: 103, synopsisTh: "ปิ่ม กลับมาเยี่ยมแม่ที่กำลังป่วยหนัก พร้อมกับสามีชาวเกาหลี แต่กลับถูกหลอกหลอนจากฝาแฝดที่เสียชีวิต", synopsisEn: "A woman returns home to care for her ill mother, haunted by the ghost of her conjoined twin.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt0970976", status: "published", viewCount: 14300, companyId: 7, company: c("gth"), genres: [g("horror"), g("thriller")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 12, slug: "a-gift-2016", titleTh: "ของขวัญ", titleEn: "A Gift", year: 2016, duration: 117, synopsisTh: "เรื่องราวของครอบครัวที่ต้องเผชิญกับความสูญเสียและการหาความหมายของชีวิต", synopsisEn: "A family deals with loss and finds meaning in unexpected places.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 6800, companyId: 1, company: c("gdh-559"), genres: [g("drama"), g("family")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 13, slug: "homestay-2018", titleTh: "โฮมสเตย์", titleEn: "Homestay", year: 2018, duration: 134, synopsisTh: "วิญญาณได้รับโอกาสกลับมาใช้ชีวิตในร่างของมิน เด็กหนุ่มที่เพิ่งเสียชีวิต แต่มีเวลาแค่ 100 วัน", synopsisEn: "A spirit gets a second chance at life in the body of a recently deceased teenager.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt7710738", status: "published", viewCount: 11200, companyId: 1, company: c("gdh-559"), genres: [g("drama"), g("thriller")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 14, slug: "tropical-malady-2004", titleTh: "สัตว์ประหลาด", titleEn: "Tropical Malady", year: 2004, duration: 118, synopsisTh: "เรื่องราวความรักระหว่างทหารหนุ่มกับชาวชนบท ที่เปลี่ยนแปลงเมื่อคนหนึ่งหายไปในป่า", synopsisEn: "A love story between a soldier and a rural man transforms into a mystical jungle odyssey.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt0381066", status: "published", viewCount: 7600, companyId: 3, company: c("five-star-production"), genres: [g("drama"), g("romance")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 15, slug: "headshot-2011", titleTh: "ฝนตกขึ้นฟ้า", titleEn: "Headshot", year: 2011, duration: 105, synopsisTh: "ตุล มือปืนที่ถูกยิงจนเห็นภาพกลับหัว ต้องเผชิญกับการเปลี่ยนแปลงในชีวิตครั้งใหญ่", synopsisEn: "A hitman survives being shot but sees the world upside down, forcing him to reconsider his life.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt1714820", status: "published", viewCount: 8900, companyId: 3, company: c("five-star-production"), genres: [g("action"), g("thriller")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 16, slug: "love-of-siam-2007", titleTh: "รักแห่งสยาม", titleEn: "Love of Siam", year: 2007, duration: 150, synopsisTh: "มิว นักร้องวงดนตรี กับ โทนี่ เพื่อนสมัยเด็ก ที่ต้องเผชิญกับความรักที่ซับซ้อนในวัยรุ่น", synopsisEn: "Two childhood friends reunite as teenagers and confront complicated feelings for each other.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt1186543", status: "published", viewCount: 17500, companyId: 2, company: c("sahamongkol-film"), genres: [g("drama"), g("romance")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 17, slug: "happy-old-year-2019", titleTh: "ฮาวทูทิ้ง..ทิ้งستان", titleEn: "Happy Old Year", year: 2019, duration: 113, synopsisTh: "จีน สาวนักออกแบบ ตัดสินใจจัดระเบียบบ้านแบบมินิมอล แต่ต้องเผชิญกับความทรงจำที่ไม่อยากจำ", synopsisEn: "A designer decides to declutter her home but must confront painful memories from her past.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt9051908", status: "published", viewCount: 9800, companyId: 1, company: c("gdh-559"), genres: [g("drama"), g("romance")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 18, slug: "iron-ladies-2000", titleTh: "สตรีเหล็ก", titleEn: "The Iron Ladies", year: 2000, duration: 104, synopsisTh: "เรื่องจริงของทีมวอลเลย์บอลกะเทยที่ชนะการแข่งขันระดับชาติ", synopsisEn: "The true story of a mostly transgender volleyball team that wins a national championship.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt0269608", status: "published", viewCount: 13600, companyId: 3, company: c("five-star-production"), genres: [g("comedy"), g("drama")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 19, slug: "one-day-2016", titleTh: "แฟนเดย์ แฟนกันแค่วันเดียว", titleEn: "One Day", year: 2016, duration: 115, synopsisTh: "หน่า สาวธรรมดาที่ฝันอยากเป็นนางเอก ได้มีโอกาสเป็นแฟนกับพระเอกดังแค่หนึ่งวัน", synopsisEn: "An ordinary girl gets to be the girlfriend of a famous actor for just one day.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 10400, companyId: 1, company: c("gdh-559"), genres: [g("romance"), g("comedy")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 20, slug: "the-medium-2021", titleTh: "ร่างทรง", titleEn: "The Medium", year: 2021, duration: 130, synopsisTh: "สารคดีตามติดร่างทรงในภาคอีสาน ที่เริ่มมีพฤติกรรมแปลกประหลาดและน่าสะพรึง", synopsisEn: "A documentary crew follows a shaman in Isan whose niece begins exhibiting disturbing behavior.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt13446168", status: "published", viewCount: 18200, companyId: 1, company: c("gdh-559"), genres: [g("horror")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 21, slug: "heart-attack-2015", titleTh: "ฟรีแลนซ์..ห้ามป่วย ห้ามพัก ห้ามรักหมอ", titleEn: "Heart Attack", year: 2015, duration: 127, synopsisTh: "ยิ่ว กราฟิกดีไซเนอร์ฟรีแลนซ์ที่ทำงานหนักจนป่วยเป็นโรคผิวหนัง ต้องไปหาหมอ", synopsisEn: "An overworked freelance designer falls ill and develops feelings for his dermatologist.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt4086058", status: "published", viewCount: 14700, companyId: 1, company: c("gdh-559"), genres: [g("romance"), g("comedy")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 22, slug: "bang-rajan-2000", titleTh: "บางระจัน", titleEn: "Bang Rajan", year: 2000, duration: 113, synopsisTh: "วีรกรรมของชาวบ้านบางระจันที่ต่อสู้กับกองทัพพม่า ก่อนการเสียกรุงศรีอยุธยาครั้งที่ 2", synopsisEn: "The story of villagers who heroically fought against the Burmese army before Ayutthaya fell.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt0268230", status: "published", viewCount: 16400, companyId: 3, company: c("five-star-production"), genres: [g("action"), g("drama")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 23, slug: "timeline-2014", titleTh: "ไทม์ไลน์ จดหมาย ความทรงจำ", titleEn: "Timeline", year: 2014, duration: 118, synopsisTh: "เรื่องราวความรักข้ามเวลาผ่านจดหมาย ระหว่างชายหนุ่มกับสาวที่ไม่เคยพบกัน", synopsisEn: "A love story that transcends time through letters between two people who never meet.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 11800, companyId: 1, company: c("gdh-559"), genres: [g("romance"), g("drama")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 24, slug: "laddaland-2011", titleTh: "ลัดดาแลนด์", titleEn: "Laddaland", year: 2011, duration: 113, synopsisTh: "ครอบครัวธีระย้ายมาอยู่หมู่บ้านจัดสรรลัดดาแลนด์ แต่กลับต้องเผชิญกับเหตุการณ์สยองขวัญ", synopsisEn: "A family moves to a suburban housing estate plagued by supernatural horrors.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt1985014", status: "published", viewCount: 15300, companyId: 1, company: c("gdh-559"), genres: [g("horror")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 25, slug: "buppah-rahtree-2003", titleTh: "บุปผาราตรี", titleEn: "Buppah Rahtree", year: 2003, duration: 105, synopsisTh: "บุปผา สาวบ้านนอกที่มาเรียนในเมือง ถูกหลอกลวงจนเสียชีวิต และกลายเป็นผีสาวที่หลอกหลอนหอพัก", synopsisEn: "A young woman from the countryside is betrayed and becomes a ghost haunting her apartment.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt0378704", status: "published", viewCount: 13200, companyId: 3, company: c("five-star-production"), genres: [g("horror"), g("comedy")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 26, slug: "chocolate-2008", titleTh: "ช็อคโกแลต", titleEn: "Chocolate", year: 2008, duration: 110, synopsisTh: "เซ็น เด็กสาวออทิสติกที่มีความสามารถพิเศษด้านการต่อสู้ ต้องตามทวงหนี้แทนแม่ที่ป่วย", synopsisEn: "An autistic girl with extraordinary martial arts abilities fights to collect debts for her ill mother.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt1183252", status: "published", viewCount: 12800, companyId: 2, company: c("sahamongkol-film"), genres: [g("action")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 27, slug: "a-tale-of-two-sisters-2022", titleTh: "สองพี่น้อง", titleEn: "A Tale of Two Sisters", year: 2022, duration: 98, synopsisTh: "สองพี่น้องที่ต้องเผชิญกับความลับของครอบครัวที่ซุกซ่อนมานาน", synopsisEn: "Two sisters must confront long-buried family secrets.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 5400, companyId: 6, company: c("gmm-tv"), genres: [g("drama"), g("thriller")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 28, slug: "inhuman-kiss-2019", titleTh: "กระสือ", titleEn: "Inhuman Kiss", year: 2019, duration: 130, synopsisTh: "สี สาวที่ต้องซ่อนความลับว่าตนเองเป็นกระสือ ขณะที่ชายสองคนในหมู่บ้านหลงรักเธอ", synopsisEn: "A young woman hides a dark secret as two men in her village fall in love with her.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: "tt7260932", status: "published", viewCount: 9100, companyId: 3, company: c("five-star-production"), genres: [g("horror"), g("romance")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 29, slug: "hungry-ghost-diner-2024", titleTh: "ร้านอาหารเปิดติดผี", titleEn: "Hungry Ghost Diner", year: 2024, duration: 115, synopsisTh: "ร้านอาหารที่เปิดให้บริการทั้งคนเป็นและคนตาย เรื่องราวตลกหลอนสุดฮา", synopsisEn: "A restaurant that serves both the living and the dead in this horror-comedy.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 7200, companyId: 1, company: c("gdh-559"), genres: [g("comedy"), g("horror")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 30, slug: "how-to-make-millions-2023", titleTh: "วิธีทำเงินล้าน", titleEn: "How to Make Millions Before Grandma Dies", year: 2023, duration: 125, synopsisTh: "เอ็ม หนุ่มขี้เกียจที่เริ่มดูแลย่าป่วยเป็นมะเร็ง หวังจะได้มรดก แต่กลับค้นพบสิ่งที่มีค่ากว่าเงิน", synopsisEn: "A lazy grandson cares for his dying grandmother hoping for inheritance, but discovers something more valuable.", posterUrl: null, backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 28500, companyId: 1, company: c("gdh-559"), genres: [g("drama"), g("comedy")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
];
