import type { Film } from "@/types";
import { genres } from "./genres";
import { companies } from "./companies";

const g = (slug: string) => genres.find((x) => x.slug === slug)!;
const c = (slug: string) => companies.find((x) => x.slug === slug)!;

export const films: Film[] = [
  // === Classic Thai Films ===
  { id: 1, slug: "bad-genius-2017", titleTh: "ฉลาดเกมส์โกง", titleEn: "Bad Genius", year: 2017, duration: 130, synopsisTh: "ลินน์ นักเรียนเก่งที่ใช้ความฉลาดโกงข้อสอบ STIC เพื่อช่วยเพื่อนที่ต้องการสมัครเข้าเรียนต่อมหาวิทยาลัยในออสเตรเลีย", synopsisEn: "A genius high school student runs an exam-cheating business that takes on international implications.", posterUrl: "/posters/bad-genius.jpg", backdropUrl: null, trailerUrl: null, imdbId: "tt6788942", status: "published", viewCount: 15420, companyId: 1, company: c("gdh-559"), genres: [g("thriller"), g("drama")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 2, slug: "pee-mak-2013", titleTh: "พี่มาก..พระโขนง", titleEn: "Pee Mak", year: 2013, duration: 105, synopsisTh: "มาก ทหารหาญที่กลับบ้านหลังสงคราม พร้อมด้วยเพื่อนทหารอีก 4 คน แต่กลับพบว่าภรรยาของเขาอาจไม่ใช่คนธรรมดา", synopsisEn: "Mak returns from war with friends to his village, but they begin to suspect his wife Nak may be a ghost.", posterUrl: "/posters/pee-mak.jpg", backdropUrl: null, trailerUrl: null, imdbId: "tt2700280", status: "published", viewCount: 22300, companyId: 7, company: c("gth"), genres: [g("comedy"), g("horror")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 3, slug: "ong-bak-2003", titleTh: "องค์บาก", titleEn: "Ong-Bak: Muay Thai Warrior", year: 2003, duration: 105, synopsisTh: "ติง ชาวบ้านจากชนบทที่ต้องเดินทางเข้ากรุงเทพฯ เพื่อตามหาเศียรพระพุทธรูปที่ถูกขโมย", synopsisEn: "A skilled Muay Thai fighter travels to Bangkok to retrieve a stolen Buddha head.", posterUrl: "/posters/ong-bak.jpg", backdropUrl: null, trailerUrl: null, imdbId: "tt0368909", status: "published", viewCount: 25600, companyId: 2, company: c("sahamongkol-film"), genres: [g("action")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 4, slug: "uncle-boonmee-2010", titleTh: "ลุงบุญมีระลึกชาติ", titleEn: "Uncle Boonmee Who Can Recall His Past Lives", year: 2010, duration: 114, synopsisTh: "ลุงบุญมีกำลังจะตาย ญาติที่เสียชีวิตไปแล้วกลับมาเยี่ยม เขาเริ่มระลึกถึงชาติที่แล้ว", synopsisEn: "A man on his deathbed is visited by the ghosts of his dead wife and missing son.", posterUrl: "/posters/uncle-boonmee.jpg", backdropUrl: null, trailerUrl: null, imdbId: "tt1588895", status: "published", viewCount: 12400, companyId: 3, company: c("five-star-production"), genres: [g("drama"), g("fantasy")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 5, slug: "how-to-make-millions-2024", titleTh: "หลานม่า", titleEn: "How to Make Millions Before Grandma Dies", year: 2024, duration: 125, synopsisTh: "เอ็ม หนุ่มขี้เกียจที่เริ่มดูแลย่าป่วยเป็นมะเร็ง หวังจะได้มรดก แต่กลับค้นพบสิ่งที่มีค่ากว่าเงิน", synopsisEn: "A lazy grandson cares for his dying grandmother hoping for inheritance, but discovers something more valuable.", posterUrl: "/posters/how-to-make-millions.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 28500, companyId: 1, company: c("gdh-559"), genres: [g("drama"), g("comedy")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },

  // === 2025 Films ===
  { id: 6, slug: "food-truck-stolen-love-2025", titleTh: "ฟู้ดทรัค ลักหมูเด้ง", titleEn: "Food Truck: Stolen Love...and Moo Deng", year: 2025, duration: 105, synopsisTh: "เรื่องราวความรักสุดฮาบนรถฟู้ดทรัค ที่มาพร้อมกับหมูเด้งสุดน่ารัก", synopsisEn: "A hilarious love story on a food truck, featuring the adorable Moo Deng.", posterUrl: "/posters/food-truck.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 18200, companyId: 1, company: c("gdh-559"), genres: [g("comedy"), g("romance")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 7, slug: "a-useful-ghost-2025", titleTh: "ผีใช้ได้ค่ะ", titleEn: "A Useful Ghost", year: 2025, duration: 130, synopsisTh: "ผีสาวที่ช่วยเหลือคนเป็นในเรื่องราวตลกแฟนตาซีสุดซึ้ง", synopsisEn: "A helpful female ghost assists the living in this touching fantasy comedy.", posterUrl: "/posters/useful-ghost.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 14300, companyId: 1, company: c("gdh-559"), genres: [g("comedy"), g("drama"), g("fantasy")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 8, slug: "sokaphiwat-2025", titleTh: "โศกาภิวัฒน์", titleEn: "Sokaphiwat", year: 2025, duration: 97, synopsisTh: "ภาพยนตร์ดราม่าแฟนตาซีสยองขวัญที่สำรวจความมืดของจิตใจมนุษย์", synopsisEn: "A drama-fantasy-horror exploring the darkness within the human mind.", posterUrl: "/posters/sokaphiwat.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 8900, companyId: 3, company: c("five-star-production"), genres: [g("drama"), g("fantasy"), g("horror")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 9, slug: "tharae-the-exorcist-2025", titleTh: "ท่าแร่ ผีชำระแค้น", titleEn: "ThaRae The Exorcist", year: 2025, duration: 120, synopsisTh: "เรื่องราวสยองขวัญที่เกิดขึ้นในชุมชนท่าแร่ จังหวัดสกลนคร", synopsisEn: "A terrifying story set in the ThaRae community, Sakon Nakhon province.", posterUrl: "/posters/tharae.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 16500, companyId: 10, company: c("phranakorn-film"), genres: [g("action"), g("horror")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 10, slug: "nak-loves-mak-2025", titleTh: "นากรักมาก มั๊กมากมาก", titleEn: "Nak Loves Mak Sooo Much!", year: 2025, duration: 105, synopsisTh: "เรื่องราวความรักสุดฮาแบบแฟนตาซีที่ได้แรงบันดาลใจจากตำนานแม่นาค", synopsisEn: "A hilarious fantasy romance inspired by the Mae Nak legend.", posterUrl: "/posters/nak-loves-mak.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 12100, companyId: 10, company: c("phranakorn-film"), genres: [g("comedy"), g("fantasy"), g("romance")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 11, slug: "bangkok-joyride-5-2025", titleTh: "บางกอกจอยไรด์ ภาค 5 รำวัง", titleEn: "Bangkok Joyride Part 5: Dancing with Death", year: 2025, duration: 154, synopsisTh: "ภาคต่อของซีรีส์สารคดีที่ตามติดชีวิตคนกรุงเทพฯ ในมุมมองที่ไม่เคยเห็น", synopsisEn: "Continuation of the documentary series following Bangkok life from unseen perspectives.", posterUrl: "/posters/bangkok-joyride-5.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 5800, companyId: 3, company: c("five-star-production"), genres: [g("documentary")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 12, slug: "attack-13-2025", titleTh: "วิญญาณเลขที่ 13", titleEn: "Attack 13", year: 2025, duration: 100, synopsisTh: "เรื่องราวสยองขวัญของวิญญาณที่หลอกหลอนในอาคารเลขที่ 13", synopsisEn: "A horror story about spirits haunting building number 13.", posterUrl: "/posters/attack-13.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 9200, companyId: 10, company: c("phranakorn-film"), genres: [g("drama"), g("horror")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 13, slug: "ha-gom-2025", titleTh: "ห่าก้อม", titleEn: "Ha Gom: The Darkness of the Soul", year: 2025, duration: 110, synopsisTh: "ภาพยนตร์สยองขวัญที่สำรวจความมืดภายในจิตวิญญาณ", synopsisEn: "A horror film exploring the darkness within the soul.", posterUrl: "/posters/ha-gom.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 7600, companyId: 2, company: c("sahamongkol-film"), genres: [g("drama"), g("horror")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 14, slug: "love-or-lie-2025", titleTh: "หักสัปปะลี่ กับคดีสีชี", titleEn: "Love or Lie", year: 2025, duration: 100, synopsisTh: "เรื่องราวรักโรแมนติกคอมเมดี้สุดฮาที่เต็มไปด้วยเรื่องหลอกลวง", synopsisEn: "A hilarious romantic comedy filled with deception and love.", posterUrl: "/posters/love-or-lie.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 8400, companyId: 1, company: c("gdh-559"), genres: [g("comedy"), g("romance")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 15, slug: "phra-ruang-2025", titleTh: "พระร่วง มหาศึกสุโขทัย", titleEn: "Phra Ruang: Rise of The Empire", year: 2025, duration: 140, synopsisTh: "มหากาพย์ทางประวัติศาสตร์ว่าด้วยการก่อตั้งอาณาจักรสุโขทัย", synopsisEn: "A historical epic about the founding of the Sukhothai Kingdom.", posterUrl: "/posters/phra-ruang.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 21000, companyId: 2, company: c("sahamongkol-film"), genres: [g("action"), g("historical")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 16, slug: "home-sweet-home-rebirth-2025", titleTh: "โฮมสวีทโฮม กำเนิดใหม่", titleEn: "Home Sweet Home: Rebirth", year: 2025, duration: 115, synopsisTh: "ภาพยนตร์แอคชันแฟนตาซีสยองขวัญที่ได้แรงบันดาลใจจากเกมชื่อดัง", synopsisEn: "An action fantasy horror inspired by the famous video game.", posterUrl: "/posters/home-sweet-home.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 11300, companyId: 2, company: c("sahamongkol-film"), genres: [g("action"), g("fantasy"), g("horror")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 17, slug: "jenny-i-love-you-2025", titleTh: "เจนนี่ ไอเลิฟยู", titleEn: "Jenny, I Love You", year: 2025, duration: 110, synopsisTh: "ภาพยนตร์ดราม่าระทึกขวัญเกี่ยวกับความรักที่ซับซ้อนและอันตราย", synopsisEn: "A drama thriller about complex and dangerous love.", posterUrl: "/posters/jenny.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 6900, companyId: 1, company: c("gdh-559"), genres: [g("drama"), g("thriller")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 18, slug: "baby-hero-2025", titleTh: "ฮีโร่บ้านทุ่ง", titleEn: "Baby Hero", year: 2025, duration: 100, synopsisTh: "เด็กน้อยจากบ้านทุ่งที่กลายเป็นฮีโร่ของหมู่บ้านในเรื่องราวตลกแอคชัน", synopsisEn: "A kid from the countryside becomes a village hero in this action comedy.", posterUrl: "/posters/baby-hero.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 7800, companyId: 10, company: c("phranakorn-film"), genres: [g("action"), g("comedy")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 19, slug: "graveyard-horror-2025", titleTh: "4 ป่าช้า", titleEn: "Graveyard Horror", year: 2025, duration: 95, synopsisTh: "เรื่องสยองขวัญจากสี่ป่าช้าที่ซ่อนความลับสุดสะพรึง", synopsisEn: "Horror stories from four graveyards hiding terrifying secrets.", posterUrl: "/posters/graveyard-horror.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 10400, companyId: 10, company: c("phranakorn-film"), genres: [g("horror")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 20, slug: "halabala-2025", titleTh: "ฮาลาบาลา", titleEn: "Halabala", year: 2025, duration: 110, synopsisTh: "ภาพยนตร์แอคชันสยองขวัญที่เกิดขึ้นในป่าลึกฮาลาบาลา", synopsisEn: "An action horror set deep in the Hala-Bala forest.", posterUrl: "/posters/halabala.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 13700, companyId: 2, company: c("sahamongkol-film"), genres: [g("action"), g("horror")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 21, slug: "the-red-envelope-2025", titleTh: "ซองแดงแต่งผี", titleEn: "The Red Envelope", year: 2025, duration: 105, synopsisTh: "เรื่องราวตลกแฟนตาซีเกี่ยวกับพิธีแต่งงานกับผี", synopsisEn: "A comedy fantasy about a ghost marriage ceremony.", posterUrl: "/posters/red-envelope.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 9800, companyId: 10, company: c("phranakorn-film"), genres: [g("action"), g("comedy"), g("fantasy")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },
  { id: 22, slug: "why-we-love-2025", titleTh: "เพราะรักต้องมี", titleEn: "Why We Love?", year: 2025, duration: 100, synopsisTh: "ภาพยนตร์โรแมนติกคอมเมดี้ที่ตั้งคำถามว่าทำไมเราถึงต้องมีความรัก", synopsisEn: "A romantic comedy questioning why we need love.", posterUrl: "/posters/why-we-love.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 8100, companyId: 1, company: c("gdh-559"), genres: [g("comedy"), g("romance")], crew: [], awards: [], createdAt: "2025-01-01", updatedAt: "2025-01-01" },

  // === 2024 Films ===
  { id: 23, slug: "uranus-2324-2024", titleTh: "ยูเรนัส 2324", titleEn: "Uranus2324", year: 2024, duration: 130, synopsisTh: "ภาพยนตร์ไซไฟโรแมนติกเกี่ยวกับความรักข้ามจักรวาล", synopsisEn: "A sci-fi romance about love across the universe.", posterUrl: "/posters/uranus2324.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 19800, companyId: 6, company: c("gmm-tv"), genres: [g("romance"), g("sci-fi")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 24, slug: "the-paradise-of-thorns-2024", titleTh: "วิมานหนาม", titleEn: "The Paradise of Thorns", year: 2024, duration: 120, synopsisTh: "ภาพยนตร์ดราม่าโรแมนติกเกี่ยวกับความรักที่เจ็บปวดแต่สวยงาม", synopsisEn: "A romantic drama about painful but beautiful love.", posterUrl: "/posters/paradise-of-thorns.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 15600, companyId: 4, company: c("channel-3"), genres: [g("drama"), g("romance")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 25, slug: "my-boo-2024", titleTh: "อนงค์", titleEn: "My Boo", year: 2024, duration: 105, synopsisTh: "เรื่องราวตลกสยองขวัญโรแมนติกเกี่ยวกับผีสาวที่ตกหลุมรักมนุษย์", synopsisEn: "A comedy horror romance about a female ghost falling in love with a human.", posterUrl: "/posters/my-boo.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 11200, companyId: 1, company: c("gdh-559"), genres: [g("comedy"), g("horror"), g("romance")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 26, slug: "haunted-universities-3-2024", titleTh: "เทอม 3", titleEn: "Haunted Universities 3", year: 2024, duration: 100, synopsisTh: "ภาคต่อของซีรีส์สยองขวัญในรั้วมหาวิทยาลัย", synopsisEn: "The continuation of the horror series set in universities.", posterUrl: "/posters/haunted-universities-3.png", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 8700, companyId: 7, company: c("gth"), genres: [g("comedy"), g("drama"), g("horror")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 27, slug: "the-cursed-land-2024", titleTh: "แดนสาป", titleEn: "The Cursed Land", year: 2024, duration: 110, synopsisTh: "ภาพยนตร์สยองขวัญเกี่ยวกับแผ่นดินที่ถูกสาปแช่ง", synopsisEn: "A horror film about a cursed land.", posterUrl: "/posters/cursed-land.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 7300, companyId: 3, company: c("five-star-production"), genres: [g("drama"), g("horror")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 28, slug: "my-exs-wedding-2024", titleTh: "ปิ๊งรัก คนที่เลิก", titleEn: "My Ex's Wedding", year: 2024, duration: 100, synopsisTh: "เรื่องราวตลกโรแมนติกเมื่อต้องไปงานแต่งงานของแฟนเก่า", synopsisEn: "A romantic comedy about attending your ex's wedding.", posterUrl: "/posters/my-exs-wedding.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 10500, companyId: 1, company: c("gdh-559"), genres: [g("comedy"), g("romance")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 29, slug: "operation-undead-2024", titleTh: "ช.พ.91 สมรภูมิคืนชีพ", titleEn: "Operation Undead", year: 2024, duration: 120, synopsisTh: "ภาพยนตร์แอคชันประวัติศาสตร์สยองขวัญเกี่ยวกับสมรภูมิรบกับกองทัพอมตะ", synopsisEn: "A historical action horror about a battle against an undead army.", posterUrl: "/posters/operation-undead.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 9400, companyId: 2, company: c("sahamongkol-film"), genres: [g("action"), g("drama"), g("historical"), g("horror")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 30, slug: "chinatown-chacha-2024", titleTh: "ไชน่าทาวน์ ชะชะ", titleEn: "Chinatown Chacha", year: 2024, duration: 110, synopsisTh: "ภาพยนตร์แอคชันตลกแฟนตาซีที่เกิดขึ้นในเยาวราช", synopsisEn: "An action comedy fantasy set in Bangkok's Chinatown.", posterUrl: "/posters/chinatown-chacha.jpg", backdropUrl: null, trailerUrl: null, imdbId: null, status: "published", viewCount: 8300, companyId: 10, company: c("phranakorn-film"), genres: [g("action"), g("comedy"), g("fantasy"), g("historical")], crew: [], awards: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
];
