import type { News } from "@/types";

export const news: News[] = [
  { id: 1, slug: "baff-2023-call-for-entry", titleTh: "เทศกาลภาพยนตร์อาเซียนแห่งกรุงเทพฯ ครั้งที่ 9 เปิดรับสมัครผลงาน", titleEn: "Bangkok ASEAN Film Festival 2023 - Call for Entry", contentTh: "เทศกาลภาพยนตร์อาเซียนแห่งกรุงเทพฯ ครั้งที่ 9 (7-12 ธ.ค. 2566) เปิดรับสมัครผู้สร้างภาพยนตร์จากภูมิภาคเอเชียตะวันออกเฉียงใต้ส่งผลงานภาพยนตร์สั้นและภาพยนตร์ขนาดยาว จัดโดยกระทรวงวัฒนธรรม", contentEn: "The 9th Bangkok ASEAN Film Festival (Dec 7-12, 2023) invites Southeast Asian filmmakers to submit short and feature-length projects.", excerptTh: "เปิดรับสมัครผลงานภาพยนตร์จากอาเซียน", coverUrl: "/news/baff-2023.jpg", tags: ["BAFF", "เทศกาลภาพยนตร์", "อาเซียน"], status: "published", viewCount: 8500, publishedAt: "2023-08-24T10:00:00Z", createdAt: "2023-08-24", updatedAt: "2023-08-24" },
  { id: 2, slug: "seapitch-awards-2021", titleTh: "ผลรางวัล SEAPITCH และการประกวดภาพยนตร์สั้นอาเซียน", titleEn: "AWARDS: SEAPITCH & ASEAN Short Film Competition", contentTh: "ผลการประกวดโครงการภาพยนตร์ SEAPITCH และภาพยนตร์สั้นอาเซียน มีผลงานจากไทย เวียดนาม และเมียนมา ได้รับรางวัล", contentEn: "Competition results highlighting award-winning projects from Thailand, Vietnam, and Myanmar.", excerptTh: "ผลรางวัลโครงการภาพยนตร์ SEAPITCH", coverUrl: "/news/seapitch-2021.jpg", tags: ["SEAPITCH", "รางวัล", "อาเซียน"], status: "published", viewCount: 5200, publishedAt: "2021-12-15T08:00:00Z", createdAt: "2021-12-15", updatedAt: "2021-12-15" },
  { id: 3, slug: "baff-2021-reservation", titleTh: "จองตั๋วเทศกาลภาพยนตร์อาเซียน BAFF 2021", titleEn: "BAFF 2021 Reservation Ticket", contentTh: "เทศกาลภาพยนตร์อาเซียน BAFF 2021 วันที่ 9-13 ธันวาคม 2564 ที่โรงภาพยนตร์ในกรุงเทพฯ เข้าชมฟรี สามารถจองตั๋วล่วงหน้าได้ที่ www.baff.go.th", contentEn: "BAFF 2021 December 9-13 at Bangkok cinemas. Free admission with advance ticket booking at www.baff.go.th", excerptTh: "จองตั๋วชมภาพยนตร์ฟรีที่เทศกาล BAFF 2021", coverUrl: "/news/baff-2021.jpg", tags: ["BAFF", "เทศกาลภาพยนตร์", "ตั๋วฟรี"], status: "published", viewCount: 12300, publishedAt: "2021-12-04T09:00:00Z", createdAt: "2021-12-04", updatedAt: "2021-12-04" },
  { id: 4, slug: "thai-film-oscars-2024", titleTh: "ภาพยนตร์ไทยเข้าชิงออสการ์ปี 2024", titleEn: "Thai Film Nominated for Oscars 2024", contentTh: "ภาพยนตร์ไทยได้รับการเสนอชื่อเข้าชิงรางวัลออสการ์ สาขาภาพยนตร์ภาษาต่างประเทศยอดเยี่ยม สร้างความภาคภูมิใจให้กับวงการภาพยนตร์ไทย", contentEn: "A Thai film has been nominated for the Academy Awards in the Best International Feature Film category.", excerptTh: "ภาพยนตร์ไทยได้รับการเสนอชื่อเข้าชิงรางวัลออสการ์", coverUrl: null, tags: ["ออสการ์", "ภาพยนตร์ไทย", "รางวัล"], status: "published", viewCount: 8500, publishedAt: "2024-12-15T10:00:00Z", createdAt: "2024-12-15", updatedAt: "2024-12-15" },
  { id: 5, slug: "content-thailand-new-website", titleTh: "เว็บไซต์ ContentThailand ปรับโฉมใหม่", titleEn: "ContentThailand Website Redesign", contentTh: "กองภาพยนตร์และวีดิทัศน์ กรมส่งเสริมวัฒนธรรม เตรียมเปิดตัวเว็บไซต์ contentthailand.com เวอร์ชันใหม่ ด้วยเทคโนโลยีล่าสุดเพื่อรองรับการใช้งานที่ดียิ่งขึ้น", contentEn: "The Bureau of Film and Video prepares to launch a redesigned contentthailand.com with the latest technology.", excerptTh: "เตรียมเปิดตัวเว็บไซต์ ContentThailand เวอร์ชันใหม่", coverUrl: null, tags: ["ContentThailand", "เว็บไซต์", "ปรับปรุง"], status: "published", viewCount: 5200, publishedAt: "2025-01-10T08:00:00Z", createdAt: "2025-01-10", updatedAt: "2025-01-10" },
  { id: 6, slug: "thai-series-global-hit", titleTh: "ซีรีส์ไทยกระแสแรงระดับโลก", titleEn: "Thai Series Becomes Global Hit", contentTh: "ซีรีส์ไทยหลายเรื่องติดอันดับ Top 10 บน Netflix ในหลายประเทศ แสดงให้เห็นถึงศักยภาพของอุตสาหกรรมบันเทิงไทยในตลาดโลก", contentEn: "Multiple Thai series rank in Netflix's Top 10 across several countries.", excerptTh: "ซีรีส์ไทยติดอันดับ Top 10 บน Netflix หลายประเทศ", coverUrl: null, tags: ["ซีรีส์ไทย", "Netflix", "ระดับโลก"], status: "published", viewCount: 12300, publishedAt: "2025-02-01T09:00:00Z", createdAt: "2025-02-01", updatedAt: "2025-02-01" },
  { id: 7, slug: "film-incentive-2025", titleTh: "มาตรการส่งเสริมการถ่ายทำภาพยนตร์ต่างชาติในไทย ปี 2568", titleEn: "Film Incentive Program 2025", contentTh: "กระทรวงวัฒนธรรมประกาศมาตรการส่งเสริมการถ่ายทำภาพยนตร์ต่างชาติในประเทศไทย ให้สิทธิประโยชน์ทางภาษีสูงสุด 30%", contentEn: "Ministry of Culture announces film incentive program offering up to 30% tax benefits for foreign productions shooting in Thailand.", excerptTh: "สิทธิประโยชน์ทางภาษีสูงสุด 30% สำหรับการถ่ายทำในไทย", coverUrl: null, tags: ["มาตรการส่งเสริม", "ภาพยนตร์ต่างชาติ", "สิทธิประโยชน์"], status: "published", viewCount: 6800, publishedAt: "2025-02-15T11:00:00Z", createdAt: "2025-02-15", updatedAt: "2025-02-15" },
  { id: 8, slug: "suphannahong-awards-2025", titleTh: "ประกาศรางวัลสุพรรณหงส์ ครั้งที่ 32", titleEn: "32nd Suphannahong Awards Announced", contentTh: "สมาพันธ์สมาคมภาพยนตร์แห่งชาติประกาศผลรางวัลสุพรรณหงส์ ครั้งที่ 32 พร้อมรายชื่อผู้ได้รับรางวัลในทุกสาขา", contentEn: "The National Federation of Motion Pictures announces the 32nd Suphannahong Awards results.", excerptTh: "ผลรางวัลสุพรรณหงส์ ครั้งที่ 32", coverUrl: null, tags: ["สุพรรณหงส์", "รางวัล", "ภาพยนตร์ไทย"], status: "published", viewCount: 9400, publishedAt: "2025-03-01T14:00:00Z", createdAt: "2025-03-01", updatedAt: "2025-03-01" },
  { id: 9, slug: "soft-power-film-2025", titleTh: "Soft Power ภาพยนตร์ไทย กลยุทธ์ใหม่เศรษฐกิจสร้างสรรค์", titleEn: "Thai Film Soft Power: New Creative Economy Strategy", contentTh: "รัฐบาลผลักดัน Soft Power ผ่านอุตสาหกรรมภาพยนตร์และวีดิทัศน์ โดยตั้งเป้าสร้างรายได้จากอุตสาหกรรมสร้างสรรค์เพิ่มขึ้น 50%", contentEn: "Government pushes Soft Power through film industry, targeting 50% increase in creative industry revenue.", excerptTh: "Soft Power ภาพยนตร์ไทย สร้างรายได้เพิ่ม 50%", coverUrl: null, tags: ["Soft Power", "เศรษฐกิจสร้างสรรค์", "ภาพยนตร์"], status: "published", viewCount: 7600, publishedAt: "2025-02-10T10:00:00Z", createdAt: "2025-02-10", updatedAt: "2025-02-10" },
  { id: 10, slug: "workshop-screenwriting-2025", titleTh: "เปิดรับสมัครอบรมการเขียนบทภาพยนตร์ รุ่น 15", titleEn: "Screenwriting Workshop Batch 15 Now Open", contentTh: "กรมส่งเสริมวัฒนธรรมเปิดรับสมัครอบรมเชิงปฏิบัติการ การเขียนบทภาพยนตร์และซีรีส์ รุ่นที่ 15 ประจำปี 2568", contentEn: "Department of Cultural Promotion opens registration for Batch 15 screenwriting workshop.", excerptTh: "เปิดรับสมัครอบรมการเขียนบทภาพยนตร์ รุ่นที่ 15", coverUrl: null, tags: ["อบรม", "เขียนบท", "ภาพยนตร์"], status: "published", viewCount: 4500, publishedAt: "2025-02-28T09:00:00Z", createdAt: "2025-02-28", updatedAt: "2025-02-28" },
];
