import type { News } from "@/types";

export const news: News[] = [
  { id: 1, slug: "thai-film-oscars-2024", titleTh: "ภาพยนตร์ไทยเข้าชิงออสการ์ปี 2024", titleEn: "Thai Film Nominated for Oscars 2024", contentTh: "ภาพยนตร์ไทยได้รับการเสนอชื่อเข้าชิงรางวัลออสการ์ สาขาภาพยนตร์ภาษาต่างประเทศยอดเยี่ยม สร้างความภาคภูมิใจให้กับวงการภาพยนตร์ไทย", contentEn: "A Thai film has been nominated for the Academy Awards in the Best International Feature Film category.", excerptTh: "ภาพยนตร์ไทยได้รับการเสนอชื่อเข้าชิงรางวัลออสการ์", coverUrl: null, tags: ["ออสการ์", "ภาพยนตร์ไทย", "รางวัล"], status: "published", viewCount: 8500, publishedAt: "2024-12-15T10:00:00Z", createdAt: "2024-12-15", updatedAt: "2024-12-15" },
  { id: 2, slug: "content-thailand-new-website", titleTh: "เว็บไซต์ ContentThailand ปรับโฉมใหม่", titleEn: "ContentThailand Website Redesign", contentTh: "กองภาพยนตร์และวีดิทัศน์ กรมส่งเสริมวัฒนธรรม เตรียมเปิดตัวเว็บไซต์ contentthailand.com เวอร์ชันใหม่ ด้วยเทคโนโลยีล่าสุดเพื่อรองรับการใช้งานที่ดียิ่งขึ้น", contentEn: "The Bureau of Film and Video prepares to launch a redesigned contentthailand.com with the latest technology.", excerptTh: "เตรียมเปิดตัวเว็บไซต์ ContentThailand เวอร์ชันใหม่", coverUrl: null, tags: ["ContentThailand", "เว็บไซต์", "ปรับปรุง"], status: "published", viewCount: 5200, publishedAt: "2025-01-10T08:00:00Z", createdAt: "2025-01-10", updatedAt: "2025-01-10" },
  { id: 3, slug: "thai-series-global-hit", titleTh: "ซีรีส์ไทยกระแสแรงระดับโลก", titleEn: "Thai Series Becomes Global Hit", contentTh: "ซีรีส์ไทยหลายเรื่องติดอันดับ Top 10 บน Netflix ในหลายประเทศ แสดงให้เห็นถึงศักยภาพของอุตสาหกรรมบันเทิงไทยในตลาดโลก", contentEn: "Multiple Thai series rank in Netflix's Top 10 across several countries, showcasing Thai entertainment industry's global potential.", excerptTh: "ซีรีส์ไทยติดอันดับ Top 10 บน Netflix หลายประเทศ", coverUrl: null, tags: ["ซีรีส์ไทย", "Netflix", "ระดับโลก"], status: "published", viewCount: 12300, publishedAt: "2025-02-01T09:00:00Z", createdAt: "2025-02-01", updatedAt: "2025-02-01" },
  { id: 4, slug: "film-incentive-2025", titleTh: "มาตรการส่งเสริมการถ่ายทำภาพยนตร์ต่างชาติในไทย ปี 2568", titleEn: "Film Incentive Program 2025", contentTh: "กระทรวงวัฒนธรรมประกาศมาตรการส่งเสริมการถ่ายทำภาพยนตร์ต่างชาติในประเทศไทย ให้สิทธิประโยชน์ทางภาษีสูงสุด 30%", contentEn: "Ministry of Culture announces film incentive program offering up to 30% tax benefits for foreign productions shooting in Thailand.", excerptTh: "สิทธิประโยชน์ทางภาษีสูงสุด 30% สำหรับการถ่ายทำในไทย", coverUrl: null, tags: ["มาตรการส่งเสริม", "ภาพยนตร์ต่างชาติ", "สิทธิประโยชน์"], status: "published", viewCount: 6800, publishedAt: "2025-02-15T11:00:00Z", createdAt: "2025-02-15", updatedAt: "2025-02-15" },
  { id: 5, slug: "suphannahong-awards-2025", titleTh: "ประกาศรางวัลสุพรรณหงส์ ครั้งที่ 32", titleEn: "32nd Suphannahong Awards Announced", contentTh: "สมาพันธ์สมาคมภาพยนตร์แห่งชาติประกาศผลรางวัลสุพรรณหงส์ ครั้งที่ 32 พร้อมรายชื่อผู้ได้รับรางวัลในทุกสาขา", contentEn: "The National Federation of Motion Pictures announces the 32nd Suphannahong Awards results.", excerptTh: "ผลรางวัลสุพรรณหงส์ ครั้งที่ 32", coverUrl: null, tags: ["สุพรรณหงส์", "รางวัล", "ภาพยนตร์ไทย"], status: "published", viewCount: 9400, publishedAt: "2025-03-01T14:00:00Z", createdAt: "2025-03-01", updatedAt: "2025-03-01" },
  { id: 6, slug: "thai-animation-industry", titleTh: "อุตสาหกรรมแอนิเมชันไทยเติบโต 25%", titleEn: "Thai Animation Industry Grows 25%", contentTh: "อุตสาหกรรมแอนิเมชันไทยเติบโต 25% ในปี 2568 ด้วยการรับงานจากต่างประเทศที่เพิ่มขึ้นและการลงทุนจากภาครัฐ", contentEn: "Thailand's animation industry grows 25% in 2025 through increased international outsourcing and government investment.", excerptTh: "แอนิเมชันไทยเติบโต 25% ในปี 2568", coverUrl: null, tags: ["แอนิเมชัน", "อุตสาหกรรม", "การเติบโต"], status: "published", viewCount: 4200, publishedAt: "2025-02-20T10:00:00Z", createdAt: "2025-02-20", updatedAt: "2025-02-20" },
  { id: 7, slug: "digital-content-strategy", titleTh: "ยุทธศาสตร์ดิจิทัลคอนเทนต์แห่งชาติ", titleEn: "National Digital Content Strategy", contentTh: "กรมส่งเสริมวัฒนธรรมร่วมกับ DEPA จัดทำยุทธศาสตร์ดิจิทัลคอนเทนต์แห่งชาติ เพื่อยกระดับอุตสาหกรรมสร้างสรรค์ไทย", contentEn: "Department of Cultural Promotion and DEPA collaborate on a national digital content strategy.", excerptTh: "ยุทธศาสตร์ดิจิทัลคอนเทนต์แห่งชาติเพื่อยกระดับอุตสาหกรรม", coverUrl: null, tags: ["ดิจิทัลคอนเทนต์", "ยุทธศาสตร์", "DEPA"], status: "published", viewCount: 3100, publishedAt: "2025-01-25T09:00:00Z", createdAt: "2025-01-25", updatedAt: "2025-01-25" },
  { id: 8, slug: "thai-film-database-update", titleTh: "ปรับปรุงฐานข้อมูลภาพยนตร์ไทย เพิ่มอีก 200 เรื่อง", titleEn: "Thai Film Database Updated with 200 New Entries", contentTh: "ContentThailand เพิ่มข้อมูลภาพยนตร์ไทยอีก 200 เรื่องในฐานข้อมูล รวมภาพยนตร์ตั้งแต่ยุคทองจนถึงปัจจุบัน", contentEn: "ContentThailand adds 200 new Thai films to the database, spanning from the golden era to present.", excerptTh: "เพิ่มข้อมูลภาพยนตร์ไทยอีก 200 เรื่อง", coverUrl: null, tags: ["ฐานข้อมูล", "ภาพยนตร์ไทย", "อัปเดต"], status: "published", viewCount: 2800, publishedAt: "2025-03-03T08:00:00Z", createdAt: "2025-03-03", updatedAt: "2025-03-03" },
  { id: 9, slug: "soft-power-film-2025", titleTh: "Soft Power ภาพยนตร์ไทย กลยุทธ์ใหม่เศรษฐกิจสร้างสรรค์", titleEn: "Thai Film Soft Power: New Creative Economy Strategy", contentTh: "รัฐบาลผลักดัน Soft Power ผ่านอุตสาหกรรมภาพยนตร์และวีดิทัศน์ โดยตั้งเป้าสร้างรายได้จากอุตสาหกรรมสร้างสรรค์เพิ่มขึ้น 50%", contentEn: "Government pushes Soft Power through film industry, targeting 50% increase in creative industry revenue.", excerptTh: "Soft Power ภาพยนตร์ไทย สร้างรายได้เพิ่ม 50%", coverUrl: null, tags: ["Soft Power", "เศรษฐกิจสร้างสรรค์", "ภาพยนตร์"], status: "published", viewCount: 7600, publishedAt: "2025-02-10T10:00:00Z", createdAt: "2025-02-10", updatedAt: "2025-02-10" },
  { id: 10, slug: "workshop-screenwriting-2025", titleTh: "เปิดรับสมัครอบรมการเขียนบทภาพยนตร์ รุ่น 15", titleEn: "Screenwriting Workshop Batch 15 Now Open", contentTh: "กรมส่งเสริมวัฒนธรรมเปิดรับสมัครอบรมเชิงปฏิบัติการ การเขียนบทภาพยนตร์และซีรีส์ รุ่นที่ 15 ประจำปี 2568", contentEn: "Department of Cultural Promotion opens registration for Batch 15 screenwriting workshop.", excerptTh: "เปิดรับสมัครอบรมการเขียนบทภาพยนตร์ รุ่นที่ 15", coverUrl: null, tags: ["อบรม", "เขียนบท", "ภาพยนตร์"], status: "published", viewCount: 4500, publishedAt: "2025-02-28T09:00:00Z", createdAt: "2025-02-28", updatedAt: "2025-02-28" },
];
