import type { TvSeries } from "@/types";
import { genres } from "./genres";
import { companies } from "./companies";

const g = (slug: string) => genres.find((x) => x.slug === slug)!;
const c = (slug: string) => companies.find((x) => x.slug === slug)!;

export const series: TvSeries[] = [
  { id: 1, slug: "buppesannivas-2018", titleTh: "บุพเพสันนิวาส", titleEn: "Love Destiny", year: 2018, endYear: 2018, episodes: 15, channel: "ช่อง 3", synopsisTh: "เกศสุรางค์ นักโบราณคดีสาวที่ถูกส่งย้อนเวลาไปในยุคสมเด็จพระนารายณ์มหาราช", synopsisEn: "A modern archaeologist is transported back to the Ayutthaya era.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 32100, companyId: 4, company: c("channel-3"), genres: [g("drama"), g("romance")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 2, slug: "hormones-the-series-2013", titleTh: "ฮอร์โมนส์ วัยว้าวุ่น", titleEn: "Hormones: The Series", year: 2013, endYear: 2015, episodes: 39, channel: "GMM 25", synopsisTh: "ชีวิตวัยรุ่นของนักเรียนมัธยมกลุ่มหนึ่ง ที่เต็มไปด้วยปัญหา ความรัก และการเติบโต", synopsisEn: "The teenage lives of high school students dealing with love, identity, and growing up.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 24500, companyId: 6, company: c("gmm-tv"), genres: [g("drama")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 3, slug: "sotus-2016", titleTh: "พี่ว้ากตัวร้ายกับนายปีหนึ่ง", titleEn: "SOTUS: The Series", year: 2016, endYear: 2017, episodes: 15, channel: "GMM 25", synopsisTh: "ระบบรับน้องของมหาวิทยาลัยที่ทำให้พี่ว้ากตัวร้ายกับน้องปีหนึ่งได้ใกล้ชิดกัน", synopsisEn: "A strict senior hazer and a rebellious freshman develop unexpected feelings.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 28700, companyId: 6, company: c("gmm-tv"), genres: [g("romance"), g("drama")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 4, slug: "girl-from-nowhere-2018", titleTh: "เด็กใหม่", titleEn: "Girl From Nowhere", year: 2018, endYear: 2021, episodes: 21, channel: "GMM 25 / Netflix", synopsisTh: "แนนโน่ นักเรียนหญิงลึกลับที่ย้ายโรงเรียนไปเรื่อย เผยความชั่วร้ายที่ซ่อนอยู่", synopsisEn: "A mysterious girl transfers between schools, exposing the hidden evils of each.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 35400, companyId: 6, company: c("gmm-tv"), genres: [g("thriller"), g("drama")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 5, slug: "2gether-2020", titleTh: "เพราะเราคู่กัน", titleEn: "2gether: The Series", year: 2020, endYear: 2020, episodes: 13, channel: "GMM 25", synopsisTh: "ไทน์ ขอให้ซาราวัตแกล้งทำเป็นแฟน เพื่อหนีรุ่นพี่ที่ตามจีบ", synopsisEn: "Tine asks Sarawat to pretend to be his boyfriend to escape an unwanted admirer.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 41200, companyId: 6, company: c("gmm-tv"), genres: [g("romance"), g("comedy")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 6, slug: "game-sanaeha-2018", titleTh: "เกมเสน่หา", titleEn: "Game Sanaeha", year: 2018, endYear: 2018, episodes: 14, channel: "ช่อง 3", synopsisTh: "ณัฐต้องแกล้งทำเป็นแฟนของอายเพื่อแก้แค้น แต่กลับตกหลุมรักเธอจริงๆ", synopsisEn: "A man pretends to be someone's boyfriend for revenge but falls in love for real.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 18900, companyId: 4, company: c("channel-3"), genres: [g("romance"), g("drama")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 7, slug: "my-ambulance-2019", titleTh: "รักฉุกเฉิน", titleEn: "My Ambulance", year: 2019, endYear: 2019, episodes: 17, channel: "ช่อง 7", synopsisTh: "รักสามเส้าระหว่างหมอ พยาบาล และหมอกู้ชีพ ท่ามกลางความเป็นความตายในห้องฉุกเฉิน", synopsisEn: "A love triangle between doctors and a paramedic unfolds in the emergency room.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 14200, companyId: 5, company: c("channel-7"), genres: [g("romance"), g("drama")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 8, slug: "bad-buddy-2021", titleTh: "แค่เพื่อนครับเพื่อน", titleEn: "Bad Buddy", year: 2021, endYear: 2022, episodes: 12, channel: "GMM 25", synopsisTh: "แพทและไพรท์ เพื่อนบ้านที่ครอบครัวเป็นศัตรูกัน แต่ทั้งคู่กลับมีความรู้สึกที่มากกว่าเพื่อน", synopsisEn: "Two boys from feuding families develop feelings that go beyond friendship.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 27800, companyId: 6, company: c("gmm-tv"), genres: [g("romance"), g("comedy")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 9, slug: "kluen-cheewit-2017", titleTh: "คลื่นชีวิต", titleEn: "Waves of Life", year: 2017, endYear: 2017, episodes: 16, channel: "ช่อง 3", synopsisTh: "สมชีวิน พระเอกพิการทางกายที่ต้องต่อสู้เพื่อความรักและศักดิ์ศรี", synopsisEn: "A physically disabled hero fights for love and dignity.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 16700, companyId: 4, company: c("channel-3"), genres: [g("drama"), g("romance")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 10, slug: "the-gifted-2018", titleTh: "นักเรียนพลังกิฟต์", titleEn: "The Gifted", year: 2018, endYear: 2018, episodes: 13, channel: "GMM 25", synopsisTh: "พัฒน์ นักเรียนธรรมดาที่ได้เข้าเรียนในห้องกิฟต์ ค้นพบว่านักเรียนทุกคนมีพลังพิเศษ", synopsisEn: "An ordinary student discovers that everyone in his gifted class has supernatural abilities.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 22100, companyId: 6, company: c("gmm-tv"), genres: [g("thriller"), g("drama")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 11, slug: "3-will-be-free-2019", titleTh: "สามทหารเสือสาว", titleEn: "3 Will Be Free", year: 2019, endYear: 2019, episodes: 10, channel: "GMM 25", synopsisTh: "สามคนหนุ่มสาวต้องหนีจากแก๊งมาเฟีย ในการเดินทางที่เปลี่ยนชีวิตพวกเขาตลอดไป", synopsisEn: "Three young people flee from a crime gang on a life-changing road trip.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 11500, companyId: 6, company: c("gmm-tv"), genres: [g("action"), g("thriller")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 12, slug: "love-in-the-air-2022", titleTh: "บรรยากาศรัก เดอะซีรีส์", titleEn: "Love in the Air", year: 2022, endYear: 2022, episodes: 12, channel: "ช่อง 3", synopsisTh: "เรื่องราวความรักของหนุ่มสองคู่ที่เต็มไปด้วยความหวานและความขัดแย้ง", synopsisEn: "The love stories of two couples filled with sweetness and conflict.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 19400, companyId: 4, company: c("channel-3"), genres: [g("romance")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 13, slug: "diary-of-tootsies-2016", titleTh: "ไดอารี่ตุ๊ดซี่ส์ เดอะซีรีส์", titleEn: "Diary of Tootsies", year: 2016, endYear: 2016, episodes: 12, channel: "GMM 25", synopsisTh: "ชีวิตของกลุ่มเพื่อนหลากหลายเพศในมหาวิทยาลัย ที่เต็มไปด้วยเรื่องตลกและซึ้ง", synopsisEn: "The colorful university life of a diverse group of friends.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 8900, companyId: 6, company: c("gmm-tv"), genres: [g("comedy"), g("drama")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 14, slug: "f4-thailand-2021", titleTh: "เอฟโฟร์ ไทยแลนด์", titleEn: "F4 Thailand: Boys Over Flowers", year: 2021, endYear: 2022, episodes: 16, channel: "GMM 25", synopsisTh: "กอร์จ สาวธรรมดาที่ได้ทุนเข้าเรียนโรงเรียนไฮโซ และต้องเผชิญกับ F4 กลุ่มรุ่นพี่สุดเพอร์เฟค", synopsisEn: "An ordinary girl enters an elite school and crosses paths with the powerful F4 clique.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 26300, companyId: 6, company: c("gmm-tv"), genres: [g("romance"), g("drama")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 15, slug: "my-school-president-2022", titleTh: "แค่ที่แกง", titleEn: "My School President", year: 2022, endYear: 2023, episodes: 12, channel: "GMM 25", synopsisTh: "ทิน ประธานนักเรียนที่ต้องกอบกู้วงดนตรีของโรงเรียน ร่วมกับกลุ่มเพื่อนสุดป่วน", synopsisEn: "A school president must save the school band with his chaotic group of friends.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 21700, companyId: 6, company: c("gmm-tv"), genres: [g("comedy"), g("drama")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
];
