import type { TvSeries } from "@/types";
import { genres } from "./genres";
import { companies } from "./companies";

const g = (slug: string) => genres.find((x) => x.slug === slug)!;
const c = (slug: string) => companies.find((x) => x.slug === slug)!;

export const series: TvSeries[] = [
  // === Classic Thai Series (popular) ===
  { id: 1, slug: "buppesannivas-2018", titleTh: "บุพเพสันนิวาส", titleEn: "Love Destiny", year: 2018, endYear: 2018, episodes: 15, channel: "ช่อง 3", synopsisTh: "เกศสุรางค์ นักโบราณคดีสาวที่ถูกส่งย้อนเวลาไปในยุคสมเด็จพระนารายณ์มหาราช", synopsisEn: "A modern archaeologist is transported back to the Ayutthaya era.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 32100, companyId: 4, company: c("channel-3"), genres: [g("drama"), g("romance"), g("historical")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 2, slug: "girl-from-nowhere-2018", titleTh: "เด็กใหม่", titleEn: "Girl From Nowhere", year: 2018, endYear: 2021, episodes: 21, channel: "GMM 25 / Netflix", synopsisTh: "แนนโน่ นักเรียนหญิงลึกลับที่ย้ายโรงเรียนไปเรื่อย เผยความชั่วร้ายที่ซ่อนอยู่", synopsisEn: "A mysterious girl transfers between schools, exposing the hidden evils of each.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 35400, companyId: 6, company: c("gmm-tv"), genres: [g("thriller"), g("drama")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 3, slug: "2gether-2020", titleTh: "เพราะเราคู่กัน", titleEn: "2gether: The Series", year: 2020, endYear: 2020, episodes: 13, channel: "GMM 25", synopsisTh: "ไทน์ ขอให้ซาราวัตแกล้งทำเป็นแฟน เพื่อหนีรุ่นพี่ที่ตามจีบ", synopsisEn: "Tine asks Sarawat to pretend to be his boyfriend to escape an unwanted admirer.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 41200, companyId: 6, company: c("gmm-tv"), genres: [g("romance"), g("comedy")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 4, slug: "bad-buddy-2021", titleTh: "แค่เพื่อนครับเพื่อน", titleEn: "Bad Buddy", year: 2021, endYear: 2022, episodes: 12, channel: "GMM 25", synopsisTh: "แพทและไพรท์ เพื่อนบ้านที่ครอบครัวเป็นศัตรูกัน แต่ทั้งคู่กลับมีความรู้สึกที่มากกว่าเพื่อน", synopsisEn: "Two boys from feuding families develop feelings that go beyond friendship.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 27800, companyId: 6, company: c("gmm-tv"), genres: [g("romance"), g("comedy")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 5, slug: "hormones-the-series-2013", titleTh: "ฮอร์โมนส์ วัยว้าวุ่น", titleEn: "Hormones: The Series", year: 2013, endYear: 2015, episodes: 39, channel: "GMM 25", synopsisTh: "ชีวิตวัยรุ่นของนักเรียนมัธยมกลุ่มหนึ่ง ที่เต็มไปด้วยปัญหา ความรัก และการเติบโต", synopsisEn: "The teenage lives of high school students dealing with love, identity, and growing up.", coverUrl: null, backdropUrl: null, trailerUrl: null, status: "published", viewCount: 24500, companyId: 6, company: c("gmm-tv"), genres: [g("drama")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },

  // === 2024 Series from ContentThailand (with poster URLs) ===
  { id: 6, slug: "6th-sense-agency-2024", titleTh: "บ้านผูกวิญญาณ", titleEn: "6th Sense Agency", year: 2024, endYear: 2024, episodes: 21, channel: "Workpoint TV", synopsisTh: "ซีรีส์ดราม่าโรแมนติกระทึกขวัญเกี่ยวกับบ้านที่ผูกวิญญาณ", synopsisEn: "A drama-romance-thriller series about a house that binds spirits.", coverUrl: "/covers/6th-sense-agency.jpg", backdropUrl: null, trailerUrl: null, status: "published", viewCount: 18900, companyId: 8, company: c("workpoint"), genres: [g("drama"), g("romance"), g("thriller")], crew: [], createdAt: "2024-06-01", updatedAt: "2024-06-01" },
  { id: 7, slug: "stage-of-number-one-2024", titleTh: "บังลังก์ลูกทุ่ง", titleEn: "Stage Of Number One", year: 2024, endYear: 2024, episodes: 24, channel: "Workpoint TV", synopsisTh: "ซีรีส์ดราม่าเกี่ยวกับเวทีลูกทุ่งที่เต็มไปด้วยการแข่งขัน", synopsisEn: "A drama series about the competitive world of Thai country music.", coverUrl: "/covers/stage-of-number-one.jpg", backdropUrl: null, trailerUrl: null, status: "published", viewCount: 14200, companyId: 8, company: c("workpoint"), genres: [g("drama")], crew: [], createdAt: "2024-03-01", updatedAt: "2024-03-01" },
  { id: 8, slug: "blondie-ancient-time-2024", titleTh: "นางทาสหัวทอง", titleEn: "Blondie In An Ancient Time", year: 2024, endYear: 2024, episodes: 22, channel: "Workpoint TV", synopsisTh: "ซีรีส์ตลกแฟนตาซีประวัติศาสตร์โรแมนติกเกี่ยวกับสาวยุคใหม่ที่ย้อนเวลาไปในอดีต", synopsisEn: "A comedy fantasy historical romance about a modern girl who travels back in time.", coverUrl: "/covers/blondie-ancient-time.jpg", backdropUrl: null, trailerUrl: null, status: "published", viewCount: 16700, companyId: 8, company: c("workpoint"), genres: [g("comedy"), g("fantasy"), g("historical"), g("romance")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 9, slug: "yajai-2024", titleTh: "รู้จักพี่ยาใจไหม", titleEn: "Yajai", year: 2024, endYear: 2024, episodes: 16, channel: "ThaiPBS", synopsisTh: "ซีรีส์ตลกโรแมนติกที่สดใสและอบอุ่นหัวใจ", synopsisEn: "A bright and heartwarming romantic comedy series.", coverUrl: "/covers/yajai.jpg", backdropUrl: null, trailerUrl: null, status: "published", viewCount: 11500, companyId: 8, company: c("workpoint"), genres: [g("comedy"), g("romance")], crew: [], createdAt: "2024-06-01", updatedAt: "2024-06-01" },
  { id: 10, slug: "eightraodinary-2024", titleTh: "8 ยอดมนุษย์ธรรมดา", titleEn: "Eightraodinary", year: 2024, endYear: 2024, episodes: 16, channel: "ThaiPBS", synopsisTh: "ซีรีส์ตลกดราม่าเกี่ยวกับ 8 คนธรรมดาที่ทำสิ่งพิเศษ", synopsisEn: "A comedy-drama about 8 ordinary people doing extraordinary things.", coverUrl: "/covers/eightraodinary.jpg", backdropUrl: null, trailerUrl: null, status: "published", viewCount: 9800, companyId: 6, company: c("gmm-tv"), genres: [g("comedy"), g("drama")], crew: [], createdAt: "2024-05-01", updatedAt: "2024-05-01" },
  { id: 11, slug: "sweet-sensory-2-2024", titleTh: "Sweet Sensory 2", titleEn: "Sweet Sensory 2", year: 2024, endYear: 2024, episodes: 8, channel: "ThaiPBS", synopsisTh: "ซีรีส์ดราม่าโรแมนติกภาคต่อที่หวานกว่าเดิม", synopsisEn: "The sweeter sequel of the drama romance series.", coverUrl: "/covers/sweet-sensory-2.png", backdropUrl: null, trailerUrl: null, status: "published", viewCount: 8200, companyId: 6, company: c("gmm-tv"), genres: [g("drama"), g("romance")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 12, slug: "city-of-stars-2024", titleTh: "เฟื่องนคร", titleEn: "City of Stars", year: 2024, endYear: 2024, episodes: 12, channel: "one31", synopsisTh: "ซีรีส์ตลกโรแมนติกที่เกิดขึ้นในเมืองกรุง", synopsisEn: "A romantic comedy series set in the city.", coverUrl: "/covers/city-of-stars.jpg", backdropUrl: null, trailerUrl: null, status: "published", viewCount: 12400, companyId: 4, company: c("channel-3"), genres: [g("comedy"), g("romance")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 13, slug: "the-doctors-2024", titleTh: "หมอตลอดกาล", titleEn: "The Doctors", year: 2024, endYear: 2024, episodes: 16, channel: "ThaiPBS", synopsisTh: "ซีรีส์ดราม่าเกี่ยวกับชีวิตของแพทย์ที่ทุ่มเทเพื่อผู้ป่วย", synopsisEn: "A drama series about the dedicated lives of doctors.", coverUrl: "/covers/the-doctors.jpg", backdropUrl: null, trailerUrl: null, status: "published", viewCount: 10100, companyId: 4, company: c("channel-3"), genres: [g("drama")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 14, slug: "once-upon-a-time-2024", titleTh: "รถรางเที่ยวสุดท้าย", titleEn: "Once Upon A Time", year: 2024, endYear: 2024, episodes: 12, channel: "ThaiPBS", synopsisTh: "ซีรีส์ดราม่าเกี่ยวกับเรื่องราวบนรถรางเที่ยวสุดท้าย", synopsisEn: "A drama series about stories on the last tram ride.", coverUrl: "/covers/once-upon-a-time.jpg", backdropUrl: null, trailerUrl: null, status: "published", viewCount: 7800, companyId: 4, company: c("channel-3"), genres: [g("drama")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
  { id: 15, slug: "beating-again-2024", titleTh: "ขยับหัวใจมาใส่จังหวะ", titleEn: "Beating Again", year: 2024, endYear: 2024, episodes: 4, channel: "ThaiPBS", synopsisTh: "ซีรีส์ตลกโรแมนติกสั้นๆ ที่ขยับหัวใจให้เต้นอีกครั้ง", synopsisEn: "A short romantic comedy series that makes your heart beat again.", coverUrl: "/covers/beating-again.jpg", backdropUrl: null, trailerUrl: null, status: "published", viewCount: 6500, companyId: 6, company: c("gmm-tv"), genres: [g("comedy"), g("romance")], crew: [], createdAt: "2024-01-01", updatedAt: "2024-01-01" },
];
